timezone: Europe/Moscow
dmami:
  group: 231-363
notify:
  telegram_bot_token: null
  telegram_chat_id: null
  on_start_summary: true
  daily_summary: true
  daily_summary_hour: 7
  daily_summary_minute: 0
  allowed_user_ids:
  - 517738418
system:
  require_ac_power: true
  keep_awake: true
chromium:
  headless: false
  executable_path: C:\Program Files\Google\Chrome\Application\chrome.exe
  use_fake_media: true
  extra_args:
  - --use-fake-device-for-media-stream
  - --use-fake-ui-for-media-stream
  - --use-file-for-fake-video-capture=assets\black.y4m
  - --use-file-for-fake-audio-capture=assets\silence.wav
  - --autoplay-policy=no-user-gesture-required
healthcheck:
  every_minutes: 5
  fail_threshold: 2
  indicators:
  - type: selector_exists
    value: 'button[aria-label*="Покинуть встречу" i], [role="button"][aria-label*="Покинуть
      встречу" i], button[aria-label="raise_hand"], [aria-label*="поднять руку" i],
      [aria-label*="Одобрить" i], [aria-label*="Approve" i], [aria-label*="Leave meeting"
      i]

      '
  - type: selector_exists
    value: button[data-testid*="ScreenSharingButton"]
  - type: selector_exists
    value: button[data-testid*="Microphone"], button[aria-label*="микроф" i], button[label*="микроф"
      i]
  - type: selector_exists
    value: div[contenteditable="true"][data-placeholder="Введите сообщение"], div[contenteditable="true"][aria-label="Введите
      сообщение"], [placeholder="Введите сообщение"]
  - type: websocket_open
  - type: webrtc_active
meetings:
- name: Проектирование интернет-приложений (Лекция)
  url: https://my.mts-link.ru/j/19400763/7931368744/session/7625531348
  cron: 20 12 * * tue
  duration_minutes: 90
  start_date: 2025-09-02       # первая пара
  end_date: 2025-11-02         # последняя пара
  join:
    steps:
    - action: wait
      selector: '#EventEnterForm'
      timeout_ms: 20000
    - action: click
      selector: '#name'
    - action: fill
      selector: '#name'
      value: Лухнев Олег 231-363
    - action: press
      selector: '#name'
      value: Tab
    - action: wait
      selector: button[data-testid='EventLanding.enter-to-event']:not([disabled])
      timeout_ms: 8000
    - action: click
      selector: button[data-testid='EventLanding.enter-to-event']
    - action: maybe_click
      selector: button[aria-label*="Выключить микрофон" i]
    - action: maybe_click
      selector: button[aria-label*="Выключить камеру" i]
    - action: wait
      selector: button:has-text("Присоединиться к встрече")
      timeout_ms: 15000
    - action: click
      selector: button:has-text("Присоединиться к встрече")
    - action: sleep
      value: 1200
    - action: maybe_click
      selector: button[aria-label*="Выключить микрофон" i]
    - action: maybe_click
      selector: button[aria-label*="Выключить камеру" i]
- name: Высокопроизводительные вычисления (Лекция)
  url: https://my.mts-link.ru/j/19400763/7931368744/session/7625531348
  cron: 20 12 * * tue
  duration_minutes: 90
  start_date: 2025-11-03       # первая пара
  end_date: 2026-01-04         # последняя пара
  join:
    steps:
    - action: wait
      selector: '#EventEnterForm'
      timeout_ms: 20000
    - action: click
      selector: '#name'
    - action: fill
      selector: '#name'
      value: Лухнев Олег 231-363
    - action: press
      selector: '#name'
      value: Tab
    - action: wait
      selector: button[data-testid='EventLanding.enter-to-event']:not([disabled])
      timeout_ms: 8000
    - action: click
      selector: button[data-testid='EventLanding.enter-to-event']
    - action: maybe_click
      selector: button[aria-label*="Выключить микрофон" i]
    - action: maybe_click
      selector: button[aria-label*="Выключить камеру" i]
    - action: wait
      selector: button:has-text("Присоединиться к встрече")
      timeout_ms: 15000
    - action: click
      selector: button:has-text("Присоединиться к встрече")
    - action: sleep
      value: 1200
    - action: maybe_click
      selector: button[aria-label*="Выключить микрофон" i]
    - action: maybe_click
      selector: button[aria-label*="Выключить камеру" i]
- name: Электронный бизнес (Лекция)
  url: https://my.mts-link.ru/j/19400927/7931431826/session/7625583409
  cron: 30 14 * * tue
  duration_minutes: 90
  start_date: 2025-09-01       # первая пара
  end_date: 2026-01-04         # последняя пара
  join:
    steps:
    - action: wait
      selector: '#EventEnterForm'
      timeout_ms: 20000
    - action: click
      selector: '#name'
    - action: fill
      selector: '#name'
      value: Лухнев Олег 231-363
    - action: press
      selector: '#name'
      value: Tab
    - action: wait
      selector: button[data-testid='EventLanding.enter-to-event']:not([disabled])
      timeout_ms: 8000
    - action: click
      selector: button[data-testid='EventLanding.enter-to-event']
    - action: maybe_click
      selector: button[aria-label*="Выключить микрофон" i]
    - action: maybe_click
      selector: button[aria-label*="Выключить камеру" i]
    - action: wait
      selector: button:has-text("Присоединиться к встрече")
      timeout_ms: 15000
    - action: click
      selector: button:has-text("Присоединиться к встрече")
    - action: sleep
      value: 1200
    - action: maybe_click
      selector: button[aria-label*="Выключить микрофон" i]
    - action: maybe_click
      selector: button[aria-label*="Выключить камеру" i]
- name: Нейронные сети (Лекция)
  url: https://my.mts-link.ru/j/19399433/6593192072/session/6354312243
  cron: 0 9 * * wed
  duration_minutes: 90
  start_date: 2025-09-01       # первая пара
  end_date: 2025-11-02         # последняя пара
  join:
    steps:
    - action: wait
      selector: '#EventEnterForm'
      timeout_ms: 20000
    - action: click
      selector: '#name'
    - action: fill
      selector: '#name'
      value: Лухнев Олег 231-363
    - action: press
      selector: '#name'
      value: Tab
    - action: wait
      selector: button[data-testid='EventLanding.enter-to-event']:not([disabled])
      timeout_ms: 8000
    - action: click
      selector: button[data-testid='EventLanding.enter-to-event']
    - action: maybe_click
      selector: button[aria-label*="Выключить микрофон" i]
    - action: maybe_click
      selector: button[aria-label*="Выключить камеру" i]
    - action: wait
      selector: button:has-text("Присоединиться к встрече")
      timeout_ms: 15000
    - action: click
      selector: button:has-text("Присоединиться к встрече")
    - action: sleep
      value: 1200
    - action: maybe_click
      selector: button[aria-label*="Выключить микрофон" i]
    - action: maybe_click
      selector: button[aria-label*="Выключить камеру" i]
- name: Нейронные сети (Лекция)
  url: https://my.mts-link.ru/j/19399433/6593192072/session/6354312243
  cron: 40 10 * * wed
  duration_minutes: 90
  start_date: 2025-09-01       # первая пара
  end_date: 2025-11-02         # последняя пара
  join:
    steps:
    - action: wait
      selector: '#EventEnterForm'
      timeout_ms: 20000
    - action: click
      selector: '#name'
    - action: fill
      selector: '#name'
      value: Лухнев Олег 231-363
    - action: press
      selector: '#name'
      value: Tab
    - action: wait
      selector: button[data-testid='EventLanding.enter-to-event']:not([disabled])
      timeout_ms: 8000
    - action: click
      selector: button[data-testid='EventLanding.enter-to-event']
    - action: maybe_click
      selector: button[aria-label*="Выключить микрофон" i]
    - action: maybe_click
      selector: button[aria-label*="Выключить камеру" i]
    - action: wait
      selector: button:has-text("Присоединиться к встрече")
      timeout_ms: 15000
    - action: click
      selector: button:has-text("Присоединиться к встрече")
    - action: sleep
      value: 1200
    - action: maybe_click
      selector: button[aria-label*="Выключить микрофон" i]
    - action: maybe_click
      selector: button[aria-label*="Выключить камеру" i]
- name: Инструменты визуализации данных (Лекция)
  url: https://my.mts-link.ru/j/19396923/6593357922/session/6354479690
  cron: 20 12 * * wed
  duration_minutes: 90
  start_date: 2025-09-01       # первая пара
  end_date: 2025-11-02         # последняя пара
  join:
    steps:
    - action: wait
      selector: '#EventEnterForm'
      timeout_ms: 20000
    - action: click
      selector: '#name'
    - action: fill
      selector: '#name'
      value: Лухнев Олег 231-363
    - action: press
      selector: '#name'
      value: Tab
    - action: wait
      selector: button[data-testid='EventLanding.enter-to-event']:not([disabled])
      timeout_ms: 8000
    - action: click
      selector: button[data-testid='EventLanding.enter-to-event']
    - action: maybe_click
      selector: button[aria-label*="Выключить микрофон" i]
    - action: maybe_click
      selector: button[aria-label*="Выключить камеру" i]
    - action: wait
      selector: button:has-text("Присоединиться к встрече")
      timeout_ms: 15000
    - action: click
      selector: button:has-text("Присоединиться к встрече")
    - action: sleep
      value: 1200
    - action: maybe_click
      selector: button[aria-label*="Выключить микрофон" i]
    - action: maybe_click
      selector: button[aria-label*="Выключить камеру" i]
- name: Инструменты визуализации данных (Лаб.работа)
  url: https://my.mts-link.ru/j/17322013/6839244634
  cron: 40 10 * * wed
  duration_minutes: 90
  start_date: 2025-09-01       # первая пара
  end_date: 2025-11-02         # последняя пара
  join:
    steps:
    - action: wait
      selector: '#EventEnterForm'
      timeout_ms: 20000
    - action: click
      selector: '#name'
    - action: fill
      selector: '#name'
      value: Лухнев Олег 231-363
    - action: press
      selector: '#name'
      value: Tab
    - action: wait
      selector: button[data-testid='EventLanding.enter-to-event']:not([disabled])
      timeout_ms: 8000
    - action: click
      selector: button[data-testid='EventLanding.enter-to-event']
    - action: maybe_click
      selector: button[aria-label*="Выключить микрофон" i]
    - action: maybe_click
      selector: button[aria-label*="Выключить камеру" i]
    - action: wait
      selector: button:has-text("Присоединиться к встрече")
      timeout_ms: 15000
    - action: click
      selector: button:has-text("Присоединиться к встрече")
    - action: sleep
      value: 1200
    - action: maybe_click
      selector: button[aria-label*="Выключить микрофон" i]
    - action: maybe_click
      selector: button[aria-label*="Выключить камеру" i]
- name: Инструменты визуализации данных (Лаб.работа)
  url: https://my.mts-link.ru/j/17322013/6839244634
  cron: 20 12 * * wed
  duration_minutes: 90
  start_date: 2025-09-01       # первая пара
  end_date: 2025-11-02         # последняя пара
  join:
    steps:
    - action: wait
      selector: '#EventEnterForm'
      timeout_ms: 20000
    - action: click
      selector: '#name'
    - action: fill
      selector: '#name'
      value: Лухнев Олег 231-363
    - action: press
      selector: '#name'
      value: Tab
    - action: wait
      selector: button[data-testid='EventLanding.enter-to-event']:not([disabled])
      timeout_ms: 8000
    - action: click
      selector: button[data-testid='EventLanding.enter-to-event']
    - action: maybe_click
      selector: button[aria-label*="Выключить микрофон" i]
    - action: maybe_click
      selector: button[aria-label*="Выключить камеру" i]
    - action: wait
      selector: button:has-text("Присоединиться к встрече")
      timeout_ms: 15000
    - action: click
      selector: button:has-text("Присоединиться к встрече")
    - action: sleep
      value: 1200
    - action: maybe_click
      selector: button[aria-label*="Выключить микрофон" i]
    - action: maybe_click
      selector: button[aria-label*="Выключить камеру" i]
